
remote_theme: broccolini/athena

title: Athena Jekyll Theme

description: A simple and elegant theme for Jekyll and GitHub Pages.

github_repo: athena # the GitHub repo name for your project

github_username: broccolini

social_link: twitter # twitter (default), instagram, medium, or dribbble

social_username: broccolini

theme_color: light # Choose from: black (default), blue, gray, magenta, orange, red, white, and yellow.

baseurl: "/ubiquitous_bobbin_boy"
